// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjsvtejqljyvglnvjmzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqc3Z0ZWpxbGp5dmdsbnZqbXpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4OTM2MTksImV4cCI6MjA1OTQ2OTYxOX0.bGyfRB3qYb59eUiJYrKbTwc3PqjBvaiS25AjqdWyDSU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);